### ISSUE TITLE
promise-it-wont-hurt/throw-an-error.js solution does not work

### ISSUE THREAD

**Issue by NicoSa** [brunops/nodeschool-solutions#2]
My solution: 

``` javascript
var badJSON  = process.argv[2]

function parsePromised(json) {
    try{
      return Promise.resolve(JSON.parse(json));
    } catch (e) {
      return Promise.reject(new Error(e));
    };
};

function consoleLogError(error){
  console.log(error.message);
};

parsePromised(badJSON).then(console.log, consoleLogError);

```

Output: 

``` sh
> promise-it-wont-hurt run program.js
SyntaxError: Unexpected token o in JSON at position 1
```

``` sh
> promise-it-wont-hurt verify program.js
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "SyntaxError: Unexpected token o in JSON at position 1" ==    "SyntaxError: Unexpected token o in JSON at position 1"
   ""                                  !=    "    at Object.parse (native)"
                                       !=    "    at /Users/nicosa/.nvm/versions/node/v6.3.0/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:6:20"
                                       !=    "    at parsePromised (/Users/nicosa/.nvm/versions/node/v6.3.0/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:4:10)"
                                       !=    "    at Object.<anonymous> (/Users/nicosa/.nvm/versions/node/v6.3.0/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:13:1)"
                                       !=    "    at Module._compile (module.js:541:32)"
                                       !=    "    at Object.Module._extensions..js (module.js:550:10)"
                                       !=    "    at Module.load (module.js:458:32)"
                                       !=    "    at tryModuleLoad (module.js:417:12)"
                                       !=    "    at Function.Module._load (module.js:409:3)"
                                       !=    "    at Module.runMain (module.js:575:10)"
                                       !=    ""

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to Throw an error didn't pass. Try again!
```

When I copy and paste the solution from nodeschool-solutions it does also not work...

Am I doing something wrong here or is this tutorial not up to date?

**Comment by brunops** [comment]
@NicoSa try `console.log(error)` instead

**Comment by NicoSa** [comment]
Will do
